all: QUARTERSHIM.BIN ABSLDR.BIN


QUARTERSHIM.BIN: QUARTERSHIM.ASM
	asmx -b2329H -e -w -C8080 QUARTERSHIM.ASM && mv QUARTERSHIM.ASM.bin QUARTERSHIM.BIN

ABSLDR.BIN: ABSLDR.ASM
	asmx -b1400H -e -w -C8080 ABSLDR.ASM && mv ABSLDR.ASM.bin ABSLDR.BIN

send: ABSLDR.BIN
	friends/h8clxfer.py -l -f ABSLDR.BIN

clean:
	rm ABSLDR.BIN QUARTERSHIM.BIN

