all: QUARTERSHIM.BIN HALFSHIM.BIN


QUARTERSHIM.BIN: QUARTERSHIM.ASM
	asmx -b2329H -e -w -C8080 QUARTERSHIM.ASM && mv QUARTERSHIM.ASM.bin QUARTERSHIM.BIN

HALFSHIM.BIN: HALFSHIM.ASM
	asmx -b1000H -e -w -C8080 HALFSHIM.ASM && mv HALFSHIM.ASM.bin HALFSHIM.BIN

send: HALFSHIM.BIN
	friends/h8clxfer.py -l -f HALFSHIM.BIN

clean:
	rm HALFSHIM.BIN QUARTERSHIM.BIN

